FROM bitnami/jasperreports

USER root

COPY lib /opt/bitnami/apache-tomcat/lib

# https://hub.docker.com/r/bitnami/jasperreports/
# https://docs.bitnami.com/oci/apps/jasperreports/administration/use-postgresql/
